### ISSUE TITLE
.NET Core platform

### ISSUE THREAD

**Issue by tobkow** [MoonStorm/Dapper.FastCRUD#32]
I am working on a project in ASP.NET Core. Can you make a package without the dependency on StringInterpolationBridge because it is not compatible with .NET Core 5.0 and makes the whole Dapper.FastCRUD package unusable when trying to play around with it in e.g. ASP.NET Core ?

**Comment by MoonStorm** [comment]
I'll take a look.

**Comment by MoonStorm** [comment]
Don't believe the string interpolation dependency is the only problem when it comes to targeting DNX  Core. I tried to get a simple project running and failed miserably. All I wanted to do is to use Dapper to access a SQL Server database. Couldn't even locate the NuGet package that contains the SqlConnection. Could you post a very simple example project with Dapper?

**Comment by tobkow** [comment]
Sure, no problem. I attach it to this message. The connection string now contains dummy data from my example DB, it is located appsettings.json, please adjust it as well as ExampleObject to match example data from the DB of your choice. The query is located in DapperRepos/DapperRepo.cs. Please remember about selecting all CLR Exceptions in Exceptions Settings tab because otherwise you will see no eventual error messages, etc. as this example is dead simple and dead blank (in terms of ASP.NET configuration).
[DapperExample.zip](https://github.com/MoonStorm/Dapper.FastCRUD/files/240139/DapperExample.zip)

**Comment by gthelp** [comment]
any update on how this issue is going? I tried to update to Core RC2 with fastcrud 2.3.2 and getting failure not supported. Any suggestions?

Thanks

**Comment by MoonStorm** [comment]
Thanks @tobkow 

@gthelp working on it

**Comment by MoonStorm** [comment]
Thanks @tobkow Your example pointed me in the right direction, problem is the code requires plenty of ``#if`` for ``IDbConnection`` and ``IDbTransaction`` just to name a couple, which got moved to a different namespace (from ``System.Data`` to ``System.Data.Common``)  .

Also the reflection API seems to be incomplete, I get a lot of errors because of that. 

All in all I'm afraid we won't be seeing a version of ``FastCrud`` compatible with Core for the time being, but what I'm gonna do is to attempt to switch to the new project format, that way people can come and help patch it up.

**Comment by tobkow** [comment]
OK, I have copied all sources from Dapper.FastCRUD folder to our Dapper.Example, I have added a new project and now I have a version that builds. Here is a list of things I did:

1. Replaced all interfaces like `IDbConnection`, `IDbTransaction` with abstract counterparts `DbConnection`, `DbTransaction`, etc. (ref. http://stackoverflow.com/questions/27900493/asp-vnext-core-5-0-datatable)
2. Replaced `StringComparison.InvariantCultureIgnoreCase` with `StringComparison.OrdinalIgnoreCase` (ref. http://stackoverflow.com/questions/14600694/where-has-stringcomparison-invariantcultureignorecase-gone).
3. Replaced type `PropertyDescriptor` from `System.ComponentModel` with `PropertyInfo` from `System.Reflection` namespace
4. Replaced all entries related to ProperyDescriptor that used statements like` propertyType.IsEnum` or `propertyType.IsGenericTypeDefinition` etc. with `propertyType.GetTypeInfo().IsEnum` and `propertyType.GetTypeInfo().IsGenericTypeDefinition` etc.
5. Replaced all statements that were extracting properties this way `propDesc.Attributes.OfType<NotMappedAttribute>` to `propDesc.GetCustomAttributes<NotMappedAttribute>()`
6. Replaced `MetadataTypeAttribute` with `ModelMetadataTypeAttribute` (this is CONTROVERSIAL because `ModelMetadataTypeAttribute` requires `Microsoft.AspNet.Mvc.Core ` package, needs discussion, ref. http://stackoverflow.com/questions/35108694/metadatatypeattribute-not-available-in-dnx-core-5-0)
7. As a natural consequence of points 3 & 6, all statements like `TypeDescriptor.GetAttributes(entityType).OfType<MetadataTypeAttribute>()` became `entityType.GetTypeInfo().GetCustomAttributes<ModelMetadataTypeAttribute>()` and statements like `TypeDescriptor.GetProperties(entityMetadataAttribute.MetadataClassType).OfType<PropertyDescriptor>()` became `entityMetadataAttribute.MetadataType.GetProperties()`
8. Replaced `RegexOptions.Compiled` is not a part of RC1 so I replaced it with `RegexOptions.CultureInvariant` (I will try the whole procedure with RC2 in a few days, did not have time to look at it)
9. I could not get the `ToString(CultureInfo)` override to work, so I removed it to have standard `ToString()`

As you can see there are several issues to consider. I will try with RC2 and in the mean time if you branch out a .NET Core project with sources we may start working on it as well.

[DapperFastCRUDBuildingRC1.zip](https://github.com/MoonStorm/Dapper.FastCRUD/files/272163/DapperFastCRUDBuildingRC1.zip)

**Comment by MoonStorm** [comment]
Good job. I'll go through your findings and integrate them into the existing code. I do want to have a single code base for all the platforms, so ``#if``s will be necessary. It would be ideal for all of us to work on the same code rather than branching out.

I got the ``Dapper`` source code and will get some inspiration from there as well when it comes to targeting multiple platforms.

**Comment by MoonStorm** [comment]
I've created a new branch ``multi-platform`` where I created the solution ``Dapper.FastCRUD-AllPlatforms.sln`` and the corresponding project file targeting RC2. I don't quite understand why the latest version of ``Dapper`` for RC2 now extends ``DbConnection`` instead of ``IDBConnection``. Also, it seems the missing reflection methods on the ``TypeConverter`` and their respective data structures  exist in the [main repo](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs) but not in the latest packages, reason why I'd suggest we wait for the next release of the ``System.ComponentModel.TypeConverter`` package before going ahead and make changes.

**Comment by tobkow** [comment]
Thanks. Yes, it sounds reasonable to wait for updated `System.ComponentModel.TypeConverter` package. Hopefully the whole process will not require many changes in the end (interfaces coming back as a good example).

**Comment by DaGnoZ** [comment]
`System.ComponentModel.TypeConverter` has been update 2016-06-27 according to https://www.nuget.org/packages/System.ComponentModel.TypeConverter/

I'm very interessed by .NET Core support.

**Comment by MoonStorm** [comment]
We'll take another look. For everyone interested in contributing, use the master branch.

**Comment by MoonStorm** [comment]
Indeed, it was much easier now to compile for .NET Standard 1.6 / .NET Core 1.0. 
I published a preview package on NuGet. 

I'm still working on getting the new platform covered by tests.

**Comment by gthelp** [comment]
I created a new RC2 project for framework 4.6.1 and installed latest dapper 2.4.0-preview00011
Getting problem
warn : Detected package downgrade: System.Reflection.Extensions from 4.1.0 to 4.0.1 
warn :  EupR2 (>= 1.0.0) -> Dapper.FastCrud (>= 2.4.0-preview00011) -> System.Reflection.Extensions (>= 4.1.0) 
warn :  EupR2 (>= 1.0.0) -> System.Reflection.Extensions (>= 4.0.1)

Can't find a version 4.1 for system.reflection.extensions in nuget.
Do I need framework 4.6.2 preview or is the version nr wrong on fastcrud package?

Thanks

Greg
