### ISSUE TITLE
`Id` property as key by default

### ISSUE THREAD

**Issue by moxplod** [MoonStorm/Dapper.FastCRUD#5]
Btw. love what you are doing and thanks for the benchmarks. I had started using SimpleCRUD. When i stumbled upon this.

My question is would those entities directly work or do i need to regenerate them using the t4 templates you have provided? 

In SimpleCRUD just having an Id named filed was enough. Do i have to decorate all Ids with 
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]

Thanks,
Mohit

**Comment by MoonStorm** [comment]
No, you can do it at runtime as well. Unfortunately there is no magic yet to automatically guess the ID fields for you.

**Comment by MoonStorm** [comment]
Thought about this a bit more and it's still debatable. 
We could add some magic in there. However people can have entities with the primary keys not auto-generated by the database. In addition to that, I have no idea where the magic should stop, as many people use ``<Entity_Name>Id`` rather than a simple ``Id``. I've certainly used it like that for as long as I can remember. 

I suppose we could check for both situations and pick as default a property like this to be a db generated primary key, but only if there were no attributes detected on both properties and class.

**Comment by MoonStorm** [comment]
Released in 2.2 BETA. Please check the updated docs for more info.
